### ISSUE TITLE
老师你好

### ISSUE THREAD

**Issue by duang33** [tanmlh/Optimal-Neighboring-Reconstruction-for-Hyperspectral-Band-Selection#1]
在代码中，进行求Delta这个逆矩阵操作的时候，为什么输入的不是降维后的X而是Sigma呢
![zzzzz](https://user-images.githubusercontent.com/55522258/88151816-bd54b680-cc35-11ea-8a38-b252090989c5.png)

**Comment by duang33** [comment]
![zzzzz](https://user-images.githubusercontent.com/55522258/88151882-cf365980-cc35-11ea-8618-56fa3727f1ae.png)

**Comment by tanmlh** [comment]
这个其实是可以证明代码中的X' * X和Y' * Y是相等的，用哪个都可以。

**Comment by duang33** [comment]
老师多谢啦

**Comment by tanmlh** [comment]
客气了，另外我还是学生:)
