### ISSUE TITLE
你好，运行 evaluation.m出错，能否指点一二？

### ISSUE THREAD

**Issue by coco1994** [tanmlh/Optimal-Neighboring-Reconstruction-for-Hyperspectral-Band-Selection#2]
>> evaluation
函数或变量 'knnclassify' 无法识别。

出错 test_bs_accu (line 50)
            predict_label = knnclassify(bs_test_X, bs_train_X, train_labels, 3, 'euclidean');

出错 evaluation (line 75)
                cur_accu = test_bs_accu(Methods{1, 1}.band_set{dataset_id, 1}, Dataset, classifier_names{classifier_id});

**Comment by tanmlh** [comment]
这个应该是Matlab版本不同的原因，可以吧knnclassify换成你这个版本的Matlab对应的knn分类函数

**Comment by duang33** [comment]
> 
> 
> 这个应该是Matlab版本不同的原因，可以吧knnclassify换成你这个版本的Matlab对应的knn分类函数

同学你好， 上次看过你们实验室发的一个方法里面有E-FDPC方法的代码， 我运行出来后选出来的波段跟ONR原论文里的效果差异很大，能不能加个联系方式求教一下（0.0）

**Comment by coco1994** [comment]
> > > evaluation
> > > 函数或变量 'knnclassify' 无法识别。
> 
> 出错 test_bs_accu (line 50)
> predict_label = knnclassify(bs_test_X, bs_train_X, train_labels, 3, 'euclidean');
> 
> 出错 evaluation (line 75)
> cur_accu = test_bs_accu(Methods{1, 1}.band_set{dataset_id, 1}, Dataset, classifier_names{classifier_id});
